/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication6;

/**
 *
 * @author Tiffany
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Arrays;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form RegisterForm
     */
    public RegisterForm() {
         initComponents();
        this.setLocationRelativeTo(null); //To Center Form
        groupCurrency.add(jRadioButtonEuro);
        groupCurrency.add(jRadioButtonKsh);
        groupCurrency.add(jRadioButtonUSD);
        
        groupTitle.add(jRadioButtonMiss);
        groupTitle.add(jRadioButtonMr);
        groupTitle.add(jRadioButtonMrs);
        
        groupAccType.add(jRadioButtonSavAcc);
        groupAccType.add(jRadioButtonMoneyMrkt);
        groupAccType.add(jRadioButtonTiDeposit);
        groupAccType.add(jRadioButtonCheckAcc);
        
        groupYesNo.add(jRadioButtonYes);
        groupYesNo.add(jRadioButtonNo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton2 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabelUsername = new javax.swing.JLabel();
        jLabelUsername1 = new javax.swing.JLabel();
        jTextFieldEnterNo = new javax.swing.JTextField();
        jTextFieldEnterFname = new javax.swing.JTextField();
        jLabelUsername2 = new javax.swing.JLabel();
        jLabelUsername3 = new javax.swing.JLabel();
        jLabelUsername4 = new javax.swing.JLabel();
        jRadioButtonSavAcc = new javax.swing.JRadioButton();
        jRadioButtonTiDeposit = new javax.swing.JRadioButton();
        jRadioButtonCheckAcc = new javax.swing.JRadioButton();
        jRadioButtonMoneyMrkt = new javax.swing.JRadioButton();
        jRadioButtonKsh = new javax.swing.JRadioButton();
        jRadioButtonUSD = new javax.swing.JRadioButton();
        jRadioButtonEuro = new javax.swing.JRadioButton();
        jRadioButtonMr = new javax.swing.JRadioButton();
        jRadioButtonMrs = new javax.swing.JRadioButton();
        jRadioButtonMiss = new javax.swing.JRadioButton();
        jLabelUsername5 = new javax.swing.JLabel();
        jTextFieldEnterLName = new javax.swing.JTextField();
        jTextFieldEnterEmail = new javax.swing.JTextField();
        jLabelUsername6 = new javax.swing.JLabel();
        jLabelUsername7 = new javax.swing.JLabel();
        jTextFieldEnterNationality = new javax.swing.JTextField();
        jLabelUsername8 = new javax.swing.JLabel();
        jTextFieldEnterOccupation = new javax.swing.JTextField();
        jTextFieldEnterAddress = new javax.swing.JTextField();
        jLabelUsername9 = new javax.swing.JLabel();
        jLabelUsername10 = new javax.swing.JLabel();
        jTextFieldEnterCitizenship = new javax.swing.JTextField();
        jLabelUsername11 = new javax.swing.JLabel();
        jTextFieldEnterEmployer = new javax.swing.JTextField();
        jLabelUsername12 = new javax.swing.JLabel();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jLabelUsername13 = new javax.swing.JLabel();
        jCheckBoxAgree = new javax.swing.JCheckBox();
        jLabelUsername14 = new javax.swing.JLabel();
        jTextFieldEnterID = new javax.swing.JTextField();
        jButtonRegister = new javax.swing.JButton();
        jLabelPassword = new javax.swing.JLabel();
        jLabelPassword1 = new javax.swing.JLabel();
        jPasswordFieldEnterPass = new javax.swing.JPasswordField();
        jPasswordFieldEnterPassRE = new javax.swing.JPasswordField();
        jLabelUsername15 = new javax.swing.JLabel();
        //dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jTextField1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabelUserlogin1 = new javax.swing.JLabel();
        jLabelExit1 = new javax.swing.JLabel();
        jLabelMinimize1 = new javax.swing.JLabel();

        jRadioButton2.setText("jRadioButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(0, 0, 153));

        jLabelUsername.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername.setText("Currency:");

        jLabelUsername1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername1.setText("Account Type:");

        jTextFieldEnterNo.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterNo.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldEnterFname.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterFname.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsername2.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername2.setText("Title");

        jLabelUsername3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername3.setText("Telephone Number:");

        jLabelUsername4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername4.setText("Last Name:");

        jRadioButtonSavAcc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonSavAcc.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonSavAcc.setText("Savings Account");

        jRadioButtonTiDeposit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonTiDeposit.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonTiDeposit.setText("Time Deposit");

        jRadioButtonCheckAcc.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonCheckAcc.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonCheckAcc.setText("Checking Account");
        jRadioButtonCheckAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCheckAccActionPerformed(evt);
            }
        });

        jRadioButtonMoneyMrkt.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonMoneyMrkt.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMoneyMrkt.setText("Money Market");

        jRadioButtonKsh.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButtonKsh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonKsh.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonKsh.setText("KenyanShillings");

        jRadioButtonUSD.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonUSD.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonUSD.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonUSD.setText("USD");

        jRadioButtonEuro.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonEuro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonEuro.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonEuro.setText("EURO");

        jRadioButtonMr.setBackground(new java.awt.Color(51, 51, 51));
        jRadioButtonMr.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonMr.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMr.setText("MR");
        jRadioButtonMr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMrActionPerformed(evt);
            }
        });

        jRadioButtonMrs.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonMrs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonMrs.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMrs.setText("MRS");

        jRadioButtonMiss.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonMiss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonMiss.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonMiss.setText("Miss");

        jLabelUsername5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername5.setText("First Name:");

        jTextFieldEnterLName.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterLName.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldEnterEmail.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterEmail.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsername6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername6.setText("Email Address:");

        jLabelUsername7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername7.setText("Nationality:");

        jTextFieldEnterNationality.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterNationality.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsername8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername8.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername8.setText("Occupation:");

        jTextFieldEnterOccupation.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterOccupation.setForeground(new java.awt.Color(255, 255, 255));

        jTextFieldEnterAddress.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterAddress.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsername9.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername9.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername9.setText("Postal Address:");

        jLabelUsername10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername10.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername10.setText("Citizenship");

        jTextFieldEnterCitizenship.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterCitizenship.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsername11.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername11.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername11.setText("Employer:");

        jTextFieldEnterEmployer.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterEmployer.setForeground(new java.awt.Color(255, 255, 255));

        jLabelUsername12.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername12.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername12.setText("Are you Applying For A joint Account?");

        jRadioButtonYes.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonYes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonYes.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonYes.setText("Yes");

        jRadioButtonNo.setBackground(new java.awt.Color(0, 0, 0));
        jRadioButtonNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jRadioButtonNo.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButtonNo.setText("No");

        jLabelUsername13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabelUsername13.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername13.setText("If you agree with the terms and conditions of the bank click on the check box below and confirm your details beforesending your details to the bank.");

        jCheckBoxAgree.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jCheckBoxAgree.setText("I agree");

        jLabelUsername14.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername14.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername14.setText("ID Number:");

        jTextFieldEnterID.setBackground(new java.awt.Color(153, 153, 153));
        jTextFieldEnterID.setForeground(new java.awt.Color(255, 255, 255));

        jButtonRegister.setBackground(new java.awt.Color(0, 153, 204));
        jButtonRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRegister.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegister.setText("Register");
        jButtonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterActionPerformed(evt);
            }
        });

        jLabelPassword.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Password:");

        jLabelPassword1.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelPassword1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword1.setText("Retype Password:");

        jPasswordFieldEnterPass.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordFieldEnterPass.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldEnterPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldEnterPassActionPerformed(evt);
            }
        });

        jPasswordFieldEnterPassRE.setBackground(new java.awt.Color(153, 153, 153));
        jPasswordFieldEnterPassRE.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldEnterPassRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldEnterPassREActionPerformed(evt);
            }
        });

        jLabelUsername15.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabelUsername15.setForeground(new java.awt.Color(255, 255, 255));
        jLabelUsername15.setText("Date Of Birth:");

        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Go back to log in page?");
        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jRadioButtonMr))
                    .addComponent(jLabelUsername3))
                .addGap(140, 140, 140)
                .addComponent(jRadioButtonMrs)
                .addGap(223, 223, 223)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonMiss)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnterLName, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldEnterFname, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelUsername14)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldEnterID, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabelUsername9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldEnterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(249, 249, 249))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelUsername6)
                    .addComponent(jLabelUsername7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelUsername)
                                .addGap(98, 98, 98)
                                .addComponent(jRadioButtonEuro))
                            .addComponent(jCheckBoxAgree)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabelUsername13)
                        .addGap(124, 124, 124)
                        .addComponent(jButtonRegister)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelPassword1)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonYes)
                                                .addGap(116, 116, 116)
                                                .addComponent(jRadioButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelUsername12))
                                        .addGap(317, 317, 317)
                                        .addComponent(jLabelPassword)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordFieldEnterPass, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordFieldEnterPassRE, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelUsername1)
                                    .addComponent(jLabelUsername10)
                                    .addComponent(jLabelUsername11)
                                    .addComponent(jLabelUsername15))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonSavAcc)
                                                .addGap(87, 87, 87)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jRadioButtonTiDeposit)
                                                    .addComponent(jRadioButtonKsh)))
                                            .addComponent(jTextFieldEnterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEnterNo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEnterNationality, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEnterCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldEnterEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(101, 101, 101)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelUsername4)
                                            .addComponent(jRadioButtonUSD)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jRadioButtonCheckAcc)
                                                .addGap(125, 125, 125)
                                                .addComponent(jRadioButtonMoneyMrkt))
                                            .addComponent(jLabelUsername5)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabelUsername8)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldEnterOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername1)
                    .addComponent(jRadioButtonSavAcc)
                    .addComponent(jRadioButtonTiDeposit)
                    .addComponent(jRadioButtonCheckAcc)
                    .addComponent(jRadioButtonMoneyMrkt))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername)
                    .addComponent(jRadioButtonEuro)
                    .addComponent(jRadioButtonKsh)
                    .addComponent(jRadioButtonUSD))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername2)
                    .addComponent(jRadioButtonMr)
                    .addComponent(jRadioButtonMrs)
                    .addComponent(jRadioButtonMiss))
                .addGap(60, 60, 60)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername3)
                    .addComponent(jTextFieldEnterNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername5)
                    .addComponent(jTextFieldEnterFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername6)
                    .addComponent(jTextFieldEnterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername4)
                    .addComponent(jTextFieldEnterLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername7)
                    .addComponent(jTextFieldEnterNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUsername8)
                    .addComponent(jTextFieldEnterOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnterAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername9)
                            .addComponent(jLabelUsername10)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldEnterCitizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnterEmployer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername11)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnterID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelUsername14))))
                .addGap(32, 32, 32)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelUsername15)
                    .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername12)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordFieldEnterPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword1)
                    .addComponent(jPasswordFieldEnterPassRE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonYes)
                    .addComponent(jRadioButtonNo))
                .addGap(117, 117, 117)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelUsername13)
                    .addComponent(jButtonRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jCheckBoxAgree)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setForeground(new java.awt.Color(102, 102, 102));

        jLabelUserlogin1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelUserlogin1.setText("Register");

        jLabelExit1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelExit1.setText("X");
        jLabelExit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelExit1MouseClicked(evt);
            }
        });

        jLabelMinimize1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelMinimize1.setText("-");
        jLabelMinimize1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinimize1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelUserlogin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelMinimize1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelExit1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelUserlogin1)
                .addGap(22, 22, 22))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelExit1)
                    .addComponent(jLabelMinimize1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelExit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelExit1MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabelExit1MouseClicked

    private void jLabelMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinimize1MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabelMinimize1MouseClicked

    private void jRadioButtonCheckAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCheckAccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonCheckAccActionPerformed

    private void jRadioButtonMrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMrActionPerformed

    private void jPasswordFieldEnterPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldEnterPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldEnterPassActionPerformed

    private void jPasswordFieldEnterPassREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldEnterPassREActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldEnterPassREActionPerformed

    private void jButtonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterActionPerformed
        insertdata();
    }//GEN-LAST:event_jButtonRegisterActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       Homepage usl = new Homepage();
       usl.setVisible(true);
       usl.pack();
       usl.setLocationRelativeTo(null);
       usl.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.dispose();
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    private void insertdata(){
        String fname = jTextFieldEnterFname.getText();
        String lname = jTextFieldEnterLName.getText();
        String ID = jTextFieldEnterID.getText();
        String email = jTextFieldEnterEmail.getText();
        String pnumber = jTextFieldEnterNo.getText();
        String title = "Mr";
        int acctype = 1;
        int age = 0;
        //passwords
        char [] p1 = jPasswordFieldEnterPass.getPassword();
        char [] p2 = jPasswordFieldEnterPassRE.getPassword();
        if(groupTitle.getSelection().equals(jRadioButtonMr.getModel())){
            title = "Mr";
        }
        else if(groupTitle.getSelection().equals(jRadioButtonMrs.getModel())){
            title = "Mrs";
        }
        else if(groupTitle.getSelection().equals(jRadioButtonMiss.getModel())){
            title = "Miss";
        }
        if(groupAccType.getSelection().equals(jRadioButtonCheckAcc.getModel())){
            acctype = 1;
        }
        else if(groupAccType.getSelection().equals(jRadioButtonTiDeposit.getModel())){
            acctype = 3;
        }
        else if(groupAccType.getSelection().equals(jRadioButtonSavAcc.getModel())){
            acctype = 2;
        }
        else if(groupAccType.getSelection().equals(jRadioButtonMoneyMrkt.getModel())){
            acctype = 4;
        }
        if(fname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input your First Name");
        }
        if(lname.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input your Last Name");
        }
        if(ID.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input your ID Number");
        }
        if(email.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input your Email Address");
        }
        if(pnumber.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input your Phone Number");
        }
        if(Arrays.toString(p1).isEmpty() && Arrays.toString(p2).isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Input your Password");
        }
        SimpleDateFormat dob = new SimpleDateFormat("yyyy-MM-dd");
        String indt = dob.format(dateChooserCombo1.getDate());
        age = dateChooserCombo1.getDate().getYear();
        age = 2018 - age - 1900;
        String custID = null;
        Database db = new Database();
        String custSql = "INSERT INTO customerdetails(FirstName,LastName,Title,DateOfBirth,Age,PhoneNumber,IDNumber,Email) VALUES('" + fname + "','" +lname + "','" + title + "','" + indt + "','" + age + "','" + pnumber + "','" + ID + "','" + email +"')";
        if(!fname.isEmpty() && !lname.isEmpty() && !ID.isEmpty() && !email.isEmpty() && !pnumber.isEmpty())
        {
            if(Arrays.equals(p1, p2)){
                try {
                    PreparedStatement pt = db.getConnection().prepareStatement(custSql);
                    pt.executeUpdate();
                    ResultSet rscst = db.getData("customerdetails");
                    while(rscst.next()){
                        if(ID.equals(rscst.getString(8))){
                            custID = rscst.getString(1);
                        }
                    }
                    String accSql = "INSERT INTO accountdetails(idcustomerdetails,currency,idaccounttype,pass) VALUES('"+custID+"','Ksh','"+acctype+"','"+Arrays.toString(p1)+"')";
                    PreparedStatement pt2 = db.getConnection().prepareStatement(accSql);
                    pt2.executeUpdate();
                    JOptionPane.showMessageDialog(null, "Record Successfully Inserted!", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException ex) {
                    Logger.getLogger(RegisterForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup groupCurrency = new ButtonGroup();
    private ButtonGroup groupTitle = new ButtonGroup();
    private ButtonGroup groupAccType = new ButtonGroup();
    private ButtonGroup groupYesNo = new ButtonGroup();
    private com.toedter.calendar.JDateChooser dateChooserCombo1 = new com.toedter.calendar.JDateChooser(); 
    private javax.swing.JButton jButtonRegister;
    private javax.swing.JButton jButtongoBack;
    private javax.swing.JCheckBox jCheckBoxAgree;
    private javax.swing.JLabel jLabelExit1;
    private javax.swing.JLabel jLabelMinimize1;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelPassword1;
    private javax.swing.JLabel jLabelUserlogin1;
    private javax.swing.JLabel jLabelUsername;
    private javax.swing.JLabel jLabelUsername1;
    private javax.swing.JLabel jLabelUsername10;
    private javax.swing.JLabel jLabelUsername11;
    private javax.swing.JLabel jLabelUsername12;
    private javax.swing.JLabel jLabelUsername13;
    private javax.swing.JLabel jLabelUsername14;
    private javax.swing.JLabel jLabelUsername15;
    private javax.swing.JLabel jLabelUsername2;
    private javax.swing.JLabel jLabelUsername3;
    private javax.swing.JLabel jLabelUsername4;
    private javax.swing.JLabel jLabelUsername5;
    private javax.swing.JLabel jLabelUsername6;
    private javax.swing.JLabel jLabelUsername7;
    private javax.swing.JLabel jLabelUsername8;
    private javax.swing.JLabel jLabelUsername9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordFieldEnterPass;
    private javax.swing.JPasswordField jPasswordFieldEnterPassRE;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButtonCheckAcc;
    private javax.swing.JRadioButton jRadioButtonEuro;
    private javax.swing.JRadioButton jRadioButtonKsh;
    private javax.swing.JRadioButton jRadioButtonMiss;
    private javax.swing.JRadioButton jRadioButtonMoneyMrkt;
    private javax.swing.JRadioButton jRadioButtonMr;
    private javax.swing.JRadioButton jRadioButtonMrs;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonSavAcc;
    private javax.swing.JRadioButton jRadioButtonTiDeposit;
    private javax.swing.JRadioButton jRadioButtonUSD;
    private javax.swing.JRadioButton jRadioButtonYes;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldEnterAddress;
    private javax.swing.JTextField jTextFieldEnterCitizenship;
    private javax.swing.JTextField jTextFieldEnterEmail;
    private javax.swing.JTextField jTextFieldEnterEmployer;
    private javax.swing.JTextField jTextFieldEnterFname;
    private javax.swing.JTextField jTextFieldEnterID;
    private javax.swing.JTextField jTextFieldEnterLName;
    private javax.swing.JTextField jTextFieldEnterNationality;
    private javax.swing.JTextField jTextFieldEnterNo;
    private javax.swing.JTextField jTextFieldEnterOccupation;
    // End of variables declaration//GEN-END:variables
}
